package com.alten.mercato.server.model;

// Generated 2009-4-17 15:31:30 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

import net.sf.gilead.pojo.java5.LightEntity;

/**
 * Personne generated by hbm2java
 */
public class Personne extends LightEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8919650789017796165L;
	private long perId;
	private Departement departement;
	private TypePersonne typePersonne;
	private String perNom;
	private String perPrenom;
	private String perMatricule;
	private String perTrigramme;
	private Set<Departement> departements = new HashSet<Departement>(0);
	private Set<Util> utils = new HashSet<Util>(0);
	private Set<Transfert> transferts = new HashSet<Transfert>(0);

	public Personne() {
	}

	public Personne(long perId, Departement departement,
			TypePersonne typePersonne, String perNom, String perPrenom,
			String perMatricule) {
		this.perId = perId;
		this.departement = departement;
		this.typePersonne = typePersonne;
		this.perNom = perNom;
		this.perPrenom = perPrenom;
		this.perMatricule = perMatricule;
	}

	public Personne(long perId, Departement departement,
			TypePersonne typePersonne, String perNom, String perPrenom,
			String perMatricule, String perTrigramme,
			Set<Departement> departements, Set<Util> utils, Set<Transfert> transferts) {
		this.perId = perId;
		this.departement = departement;
		this.typePersonne = typePersonne;
		this.perNom = perNom;
		this.perPrenom = perPrenom;
		this.perMatricule = perMatricule;
		this.perTrigramme = perTrigramme;
		this.departements = departements;
		this.utils = utils;
		this.transferts = transferts;
	}

	/**
	 * @return the transferts
	 */
	public Set<Transfert> getTransferts() {
		return transferts;
	}

	/**
	 * @param transferts the transferts to set
	 */
	public void setTransferts(Set<Transfert> transferts) {
		this.transferts = transferts;
	}

	public long getPerId() {
		return this.perId;
	}

	public void setPerId(long perId) {
		this.perId = perId;
	}

	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	public TypePersonne getTypePersonne() {
		return this.typePersonne;
	}

	public void setTypePersonne(TypePersonne typePersonne) {
		this.typePersonne = typePersonne;
	}

	public String getPerNom() {
		return this.perNom;
	}

	public void setPerNom(String perNom) {
		this.perNom = perNom;
	}

	public String getPerPrenom() {
		return this.perPrenom;
	}

	public void setPerPrenom(String perPrenom) {
		this.perPrenom = perPrenom;
	}

	public String getPerMatricule() {
		return this.perMatricule;
	}

	public void setPerMatricule(String perMatricule) {
		this.perMatricule = perMatricule;
	}

	public String getPerTrigramme() {
		return this.perTrigramme;
	}

	public void setPerTrigramme(String perTrigramme) {
		this.perTrigramme = perTrigramme;
	}

	public Set<Departement> getDepartements() {
		return this.departements;
	}

	public void setDepartements(Set<Departement> departements) {
		this.departements = departements;
	}

	public Set<Util> getUtils() {
		return this.utils;
	}

	public void setUtils(Set<Util> utils) {
		this.utils = utils;
	}

}
