package com.alten.mercato.server.model;

import net.sf.gilead.pojo.java5.LightEntity;

// Generated 2009-4-17 15:31:30 by Hibernate Tools 3.2.4.CR1

/**
 * UtilRole generated by hbm2java
 */
public class UtilRole extends LightEntity implements java.io.Serializable {

	private long uroId;
	private Role role;
	private Util util;

	public UtilRole() {
	}

	public UtilRole(long uroId, Role role, Util util) {
		this.uroId = uroId;
		this.role = role;
		this.util = util;
	}

	public long getUroId() {
		return this.uroId;
	}

	public void setUroId(long uroId) {
		this.uroId = uroId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Util getUtil() {
		return this.util;
	}

	public void setUtil(Util util) {
		this.util = util;
	}

}
