package com.alten.mercato.server.model;

// Generated 2009-4-17 15:31:30 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

import net.sf.gilead.pojo.java5.LightEntity;

/**
 * Departement generated by hbm2java
 */
public class Departement extends LightEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1296114609518130807L;
	private long depId;
	private Personne personne;
	private String depLib;
	private Set<Personne> personnes = new HashSet<Personne>(0);

	public Departement() {
	}

	public Departement(long depId, String depLib) {
		this.depId = depId;
		this.depLib = depLib;
	}

	public Departement(long depId, Personne personne, String depLib,
			Set<Personne> personnes) {
		this.depId = depId;
		this.personne = personne;
		this.depLib = depLib;
		this.personnes = personnes;
	}

	public long getDepId() {
		return this.depId;
	}

	public void setDepId(long depId) {
		this.depId = depId;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getDepLib() {
		return this.depLib;
	}

	public void setDepLib(String depLib) {
		this.depLib = depLib;
	}

	public Set<Personne> getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Set<Personne> personnes) {
		this.personnes = personnes;
	}

}
