package com.alten.mercato.server.model;

// Generated 2009-4-17 15:31:30 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

import net.sf.gilead.pojo.java5.LightEntity;

/**
 * Util generated by hbm2java
 */
public class Util extends LightEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2221322550238358576L;
	private long utilId;
	private Personne personne;
	private String utilLogin;
	private String utilPassword;
	private Set<UtilRole> utilRoles = new HashSet<UtilRole>(0);

	public Util() {
	}

	public Util(long utilId, String utilLogin, String utilPassword) {
		this.utilId = utilId;
		this.utilLogin = utilLogin;
		this.utilPassword = utilPassword;
	}

	public Util(long utilId, Personne personne, String utilLogin,
			String utilPassword, Set<UtilRole> utilRoles) {
		this.utilId = utilId;
		this.personne = personne;
		this.utilLogin = utilLogin;
		this.utilPassword = utilPassword;
		this.utilRoles = utilRoles;
	}

	public long getUtilId() {
		return this.utilId;
	}

	public void setUtilId(long utilId) {
		this.utilId = utilId;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getUtilLogin() {
		return this.utilLogin;
	}

	public void setUtilLogin(String utilLogin) {
		this.utilLogin = utilLogin;
	}

	public String getUtilPassword() {
		return this.utilPassword;
	}

	public void setUtilPassword(String utilPassword) {
		this.utilPassword = utilPassword;
	}

	public Set<UtilRole> getUtilRoles() {
		return this.utilRoles;
	}

	public void setUtilRoles(Set<UtilRole> utilRoles) {
		this.utilRoles = utilRoles;
	}

}
